##########################################
# PRIME-RL inference config for HUD 2048 #
##########################################

gpu_memory_utilization = 0.6

[server]
host = "0.0.0.0"
port = 8000

[model]
name = "openai/gpt-oss-20b"
trust_remote_code = true
max_model_len = 32768
dtype = "auto"
enable_auto_tool_choice = true

[parallel]
tp = 1
dp = 1

