# Configuration for 2048 game environment

system_prompt: |
  You are playing a 2048 game. Your goal is to create the highest numbered tile possible by combining tiles with the same number.
  
  Game Rules:
  - The game is played on a grid (typically 4x4)
  - Tiles slide when you make a move in any direction
  - When two tiles with the same number touch, they merge into one with double the value
  - After each move, a new tile (2 or 4) appears randomly on an empty square
  - The game ends when no more moves are possible
  
  You will see the game board in ASCII format showing the current state, score, and number of moves.
  
  You have access to the following tools:
  
  - left: Move all tiles to the left
    Usage: <tool>left()</tool>
  
  - right: Move all tiles to the right
    Usage: <tool>right()</tool>
  
  - up: Move all tiles up
    Usage: <tool>up()</tool>
  
  - down: Move all tiles down
    Usage: <tool>down()</tool>
  
  - done: Indicate that you have completed playing
    Usage: <tool>done()</tool>
  
  Strategy tips:
  1. Use the <think>...</think> tags to analyze the board and plan your moves
  2. Try to keep your highest value tile in a corner
  3. Build ordered sequences of tiles
  4. Avoid filling up the board too quickly
  5. When you can't make more moves or want to stop, use the done() tool
  
  Example interaction:
  <think>Looking at the board, I should move tiles to consolidate them in one corner</think>
  <tool>left()</tool>

# Default settings
defaults:
  max_turns: 200

# Action mappings for 2048 game tools
# Each direction is exposed as a separate tool to the agent
# But they all map to the underlying MCP 'move' tool
action_mappings:
  left:
    _parser:
      positional: []
    _tool: "move"
    direction:
      static: "left"
  
  right:
    _parser:
      positional: []
    _tool: "move"
    direction:
      static: "right"
  
  up:
    _parser:
      positional: []
    _tool: "move"
    direction:
      static: "up"
  
  down:
    _parser:
      positional: []
    _tool: "move"
    direction:
      static: "down"

# Parser configuration
parser:
  xml_weight: 0.6    # Weight for XML format validation
  action_weight: 0.4  # Weight for action syntax validation

# Rubric configuration for 2048
rubric:
  weights:
    task_completion: 0.8       # Primary score from evaluation (max tile achieved)
    tool_execution: 0.1       # Successful move execution rate
    format_compliance: 0.1     # XML format and action syntax

# Logging configuration
logging:
  level: "DEBUG"