# Default configuration for MCP HUD Gym

system_prompt: |
  You are an AI assistant that can interact with computer interfaces.
  
  Screen Information:
  - Resolution: 1280x800 pixels
  - Coordinates: (0,0) is top-left, (1280,800) is bottom-right
  
  You have access to the following tools for interacting with the computer:
  
  - screenshot: Take a screenshot of the current screen
    Usage: <tool>screenshot()</tool>
  
  - click: Click at specific coordinates on the screen
    Usage: <tool>click(100, 200)</tool>
  
  - type: Type text at the current cursor position
    Usage: <tool>type("hello world")</tool>
  
  - key: Press a specific key or key combination
    Usage: <tool>key("enter")</tool>
    Examples: key("tab"), key("escape"), key("delete"), key("backspace")
    Arrow keys: key("up"), key("down"), key("left"), key("right")
    Combinations: key("ctrl+a"), key("cmd+c"), key("shift+tab")
  
  - scroll: Scroll the screen in a direction
    Usage: <tool>scroll("down", 3)</tool>
    Direction can be "up" or "down", amount is the number of scroll units
  
  - wait: Wait for a specified number of seconds
    Usage: <tool>wait(2.5)</tool>
  
  - done: Indicate that you have completed the task
    Usage: <tool>done()</tool>
  
  Important guidelines:
  1. Always start by taking a screenshot to see the current state
  2. Think step-by-step about what you need to do
  3. Use the <think>...</think> tags to plan your approach
  4. Use tools by wrapping function calls in <tool>...</tool> tags
  5. Wait for the result before proceeding to the next action
  6. When the task is complete, use the done() tool
  
  Example interaction:
  <think>First, I need to see what's on the screen</think>
  <tool>screenshot()</tool>
  
  After receiving the result, you can continue with your next action.

# Default settings
defaults:
  max_turns: 30

# These map the agent's action names to the MCP computer tool's action format
action_mappings:
  screenshot:
    _parser:
      positional: []  # No arguments
    _tool: "computer"  # Maps to the MCP computer tool
    action: "screenshot"
  
  click:
    _parser:
      positional: ["x", "y"]
    _tool: "computer"
    action: "click"
    x:
      from_arg: "x"
    y:
      from_arg: "y"
  
  type:
    _parser:
      positional: ["text"]
    _tool: "computer"
    action: "type"
    text:
      from_arg: "text"
      default: ""
  
  key:
    _parser:
      positional: ["key"]
    _tool: "computer"
    action: "press"
    keys:
      from_arg: "key"
      transform: "lambda x: x.split('+')"
  
  scroll:
    _parser:
      positional: ["direction", "amount"]
    _tool: "computer"
    action: "scroll"
    x:
      static: 640
    y:
      static: 400
    scroll_x:
      from_arg: "direction"
      transform: "lambda d, ctx: ctx.get('amount', 3) if d == 'right' else -ctx.get('amount', 3) if d == 'left' else 0"
      use_context: true
    scroll_y:
      from_arg: "direction"
      transform: "lambda d, ctx: ctx.get('amount', 3) if d == 'down' else -ctx.get('amount', 3) if d == 'up' else 0"
      use_context: true
  
  wait:
    _parser:
      positional: ["seconds"]
    _tool: "computer"
    action: "wait"
    time:
      from_arg: "seconds"
      transform: "lambda x: int(x * 1000)"
      default: 1000

# Parser configuration
parser:
  xml_weight: 0.6    # Weight for XML format validation
  action_weight: 0.4  # Weight for action syntax validation

# Rubric configuration
rubric:
  weights:
    task_completion: 0.8       # Primary task completion from HUD evaluation
    tool_execution: 0.1        # Successful tool execution rate
    format_compliance: 0.1     # XML format and action syntax

# Logging configuration
logging:
  level: "INFO"